# Generated by Django 4.1.13 on 2024-06-11 15:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Student",
        ),
    ]
