# Generated by Django 4.1.13 on 2024-06-12 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0002_delete_student"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                ("dept_id", models.AutoField(primary_key=True, serialize=False)),
                ("dept_name", models.CharField(max_length=100)),
                ("dept_email", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("stud_id", models.AutoField(primary_key=True, serialize=False)),
                ("stud_name", models.CharField(max_length=100)),
                ("stud_age", models.IntegerField()),
                ("stud_email", models.CharField(max_length=100)),
                ("stud_phone", models.BigIntegerField()),
                (
                    "stud_dept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="studentDept",
                        to="accounts.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                ("fac_id", models.AutoField(primary_key=True, serialize=False)),
                ("fac_name", models.CharField(max_length=100)),
                ("fac_age", models.IntegerField()),
                ("fac_email", models.CharField(max_length=100)),
                ("fac_phone", models.BigIntegerField()),
                (
                    "fac_dept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facultyDept",
                        to="accounts.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                ("course_id", models.AutoField(primary_key=True, serialize=False)),
                ("course_name", models.CharField(max_length=100)),
                ("course_credits", models.FloatField()),
                (
                    "course_dept",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courseDept",
                        to="accounts.department",
                    ),
                ),
            ],
        ),
    ]
