# Generated by Django 4.1.13 on 2024-06-12 16:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="department",
            name="dept_email",
        ),
    ]
