# Generated by Django 4.1.13 on 2024-06-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_remove_department_dept_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="dept_email",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
